config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "home#index"
  resources :products
  resources :products_suppliers, only: %i[ index new create show ]
  resources :items, only: %i[ index new create show ]
  resources :draft_items, only: %i[ index new create show ]
  resources :users, only: %i[ index ]
  resources :users do
    member do
      get :products
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/draft_item.rb
class DraftItem < ApplicationRecord
  belongs_to :draft_order
  belongs_to :item
end

app/models/draft_order.rb
class DraftOrder < ApplicationRecord
  has_many :draft_items
  has_many :items, through: :draft_items
  belongs_to :user
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :products_supplier
  belongs_to :store
  has_many :draft_items
  has_many :draft_orders, through: :draft_items
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :products_suppliers, dependent: :nullify
  has_many :suppliers, through: :products_suppliers
end

app/models/products_supplier.rb
class ProductsSupplier < ApplicationRecord
  belongs_to :product
  belongs_to :supplier
  has_many :items
  has_many :stores, through: :items
end

app/models/store.rb
class Store < ApplicationRecord
  has_many :items
  has_many :products_suppliers, through: :items
end

app/models/supplier.rb
class Supplier < ApplicationRecord
  has_many :products_suppliers, dependent: :nullify
  has_many :products, through: :products_suppliers
end

app/models/user.rb
class User < ApplicationRecord
  has_many :draft_orders
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/draft_items_controller.rb
class DraftItemsController < ApplicationController
  def index
    @draft_items = DraftItem.all
  end

  def new
    @options = ::FetchDraftItemsOptionsQuery.call
    @draft_item = DraftItem.new
  end

  def create
    @draft_item = DraftItem.new(draft_item_params)
    return redirect_to @draft_item if @draft_item.save

    render :new
  end

  def show
    @draft_item = DraftItem.find(params[:id])
  end

  private

  def draft_item_params
    params.require(:draft_item).permit(:item_id, :draft_order_id)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # binding.irb
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @options = ::FetchItemsOptionsQuery.call
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    return redirect_to @item if @item.save

    render :new
  end

  def show
    @item = Item.find(params[:id])
  end

  private

  def item_params
    params.require(:item).permit(:products_supplier_id, :store_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :fetch_product, only: %i[ show edit update destroy ]
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    return redirect_to @product if @product.save

    render :new
  end

  def show;end

  def edit;end

  def update
    return redirect_to @product if @product.update(product_params)

    render :edit
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price)
  end

  def fetch_product
    @product = Product.find(params[:id])
  end
end

app/controllers/products_suppliers_controller.rb
class ProductsSuppliersController < ApplicationController
  def index
    @products_suppliers = ProductsSupplier.all
  end

  def new
    @options = ::FetchProductsSuppliersOptionsQuery.call
    @products_supplier = ProductsSupplier.new
  end

  def create
    @products_supplier = ProductsSupplier.new(products_supplier_params)
    return redirect_to @products_supplier if @products_supplier.save

    render :new
  end

  def show
    @products_supplier = ProductsSupplier.find(params[:id])
  end

  private

  def products_supplier_params
    params.require(:products_supplier).permit(:product_id, :supplier_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def products
    @user = User.find(params[:id])
    @products_with_suppliers = ::FetchUsersProductsQuery.call
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/draft_items/_draft_item.html.erb
<p> 
  <%= draft_item.item.name %>
  <%= draft_item.draft_order.user.name %>
  <% if action_name == 'index' %> 
    <%= link_to "Show", draft_item %>
  <% end %>
</p>

app/views/draft_items/_form.html.erb
<%= link_to "Index", draft_items_path %>
<%= form_with model: @draft_item do |form| %>
  <%= form.label :draft_order_id, "Draft Order"  %>
  <%= form.collection_select :draft_order_id, options.select{ |opt| opt.table == 'draft_order'}, :id, :name, prompt: "Select a order" %>
  <br>

  <%= form.label :item_id , "Item" %>
  <%= form.collection_select :item_id, options.select{ |opt| opt.table == 'item'}, :id, :name, prompt: "Select a item" %>
  <br>
  
  <%= form.submit %>
<% end %>

app/views/draft_items/index.html.erb
<h1>Draft Items</h1>
<%= link_to "New" , new_draft_item_path %>
<%= render @draft_items %>

app/views/draft_items/new.html.erb
<h1>New</h1>
<%= render 'form', draft_item: @draft_item, options: @options %>

app/views/draft_items/show.html.erb
<h1>Draft Item</h1>
<%= link_to "Index", draft_items_path %>
<%= render @draft_item %>

app/views/home/index.html.erb
<h1>Start</h1>
<%= link_to "products", products_path %>
<%= link_to "products_suppliers", products_suppliers_path %>
<%= link_to "items", items_path %>

app/views/items/_form.html.erb
<%= link_to "Index", items_path %>
<%= form_with model: @item do |form| %>
  <%= form.label "name", :name %>
  <%= form.text_field :name %>   
  <br>
  <%= form.label :products_supplier_id, "Product"  %>
  <%= form.collection_select :products_supplier_id, options.select{ |opt| opt.table == 'products_supplier'}, :id, :name, prompt: "Select a product" %>
  <br>

  <%= form.label :store_id , "Store" %>
  <%= form.collection_select :store_id, options.select{ |opt| opt.table == 'store'}, :id, :name, prompt: "Select a store" %>
  <br>
  
  <%= form.submit %>
<% end %>

app/views/items/_item.html.erb
<p> 
  <%= item.products_supplier.product.name %>
  <%= item.products_supplier.supplier.name %>
  <%= item.store.name %>
  <% if action_name == 'index' %> 
    <%= link_to "Show", item %>
  <% end %>
</p>

app/views/items/index.html.erb
<h1>Items</h1>
<%= link_to "New" , new_item_path %>
<%= render @items %>

app/views/items/new.html.erb
<h1>New</h1>
<%= render 'form', item: @item, options: @options %>

app/views/items/show.html.erb
<h1>Item</h1>
<%= link_to "Index", items_path %>
<%= render @item %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Exchange Product" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= link_to "Index" , products_path %>
<%= form_with model: product do |form| %>
  <%= form.label "name", :name %>
  <%= form.text_field :name %>   
  <br>

  <%= form.label "price", :price %>
  <%= form.number_field :price, step: 0.01 %> 
  <br>
  
  <%= form.submit %>
<% end %>

app/views/products/_product.html.erb
<p> 
  <%= product.name %>
  <%= product.price %>
  <% if action_name == 'index' %> 
    <%= link_to "Show", product %>
    <%= link_to "Edit", edit_product_path(product) %>
    <%= link_to "Delete", product_path(product), data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
  <% end %>
</p>

app/views/products/edit.html.erb
<h1>Edit</h1>
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<h1>Products</h1>
<%= link_to "New" , new_product_path %>
<%= render @products %>

app/views/products/new.html.erb
<h1>New</h1>
<%= render 'form', product: @product %>

app/views/products/show.html.erb
<h1>Product</h1>
<%= link_to "Index" , products_path %>
<%= render @product %>

app/views/products_suppliers/_form.html.erb
<%= link_to "Index", products_suppliers_path %>
<%= form_with model: @products_supplier do |form| %>
  <%= form.label :product_id, "Product"  %>
  <%= form.collection_select :product_id, options.select{ |opt| opt.table == 'product'}, :id, :name, prompt: "Select a product" %>
  <br>

  <%= form.label :supplier_id , "Supplier" %>
  <%= form.collection_select :supplier_id, options.select{ |opt| opt.table == 'supplier'}, :id, :name, prompt: "Select a supplier" %>
  <br>
  
  <%= form.submit %>
<% end %>

app/views/users/_user.html.erb
<p> 
  <%= user.name %>
  <% if action_name == 'index' %> 
    <%= link_to "Show Products", products_user_path(user) %>
  <% end %>
</p>

app/views/users/index.html.erb
<h1>Users</h1>
<%= render @users %>

app/views/users/products.html.erb
<h1>Produtos Comprados por <%= @user.name %></h1>

<ul>
  <% @products_with_suppliers.each do |product| %>
    <li>
      <strong>Produto:</strong> <%= product.product_name %> - 
      <strong>Fornecedor:</strong> <%= product.supplier_name %>
    </li>
  <% end %>
</ul>

<%= link_to 'Voltar', users_path, class: 'button' %>